### ISSUE TITLE
crash with org.gnome.Platform 3.30

### ISSUE THREAD

**Issue by saivert** [saivert/deadbeef-flatpak#1]
Earlier versions work and also org.freedesktop.Platform 18.08.

```
Thread 1 "deadbeef-gtkui" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c72039 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff6c72039 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff6c51dc9 in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff78fa745 in ?? () from /app/lib/deadbeef/ddb_gui_GTK3.so
#3  0x00007ffff6b64f68 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6b65358 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6b653f0 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff6d7509d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff78c7f9a in gtkui_thread () from /app/lib/deadbeef/ddb_gui_GTK3.so
#8  0x00007ffff78c8046 in ?? () from /app/lib/deadbeef/ddb_gui_GTK3.so
#9  0x00005555555890b0 in ?? ()
#10 0x00007ffff7c660d3 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#11 0x000055555558929e in ?? ()

```

**Comment by saivert** [comment]
Seems like this is an race condition in DeaDBeeF's code.

This patch seems to fix it:

```diff
--- a/plugins/gtkui/plcommon.c	2019-05-24 23:54:31.482090891 +0200
+++ b/plugins/gtkui/plcommon.c	2019-05-26 15:01:51.175529852 +0200
@@ -173,7 +173,9 @@
 
 static void
 coverart_release (void *user_data) {
-    g_idle_add(coverart_release_cb, user_data);
+    col_info_t *info = user_data;
+    g_object_unref(info->listview->list);
+    free(user_data);
 }
 
 void
```
